-- Code generated by dvo xql. DO NOT EDIT.
-- Generated at: 2025-12-17 17:31:10

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT PRIMARY KEY,
    email TEXT UNIQUE,
    nick_name varchar(100) NOT NULL UNIQUE DEFAULT 'anonymous',
    balance DOUBLE,
    created_at DATETIME,
    updated_at DATETIME
);
CREATE INDEX IF NOT EXISTS idx_accounts_email ON accounts (email);



