-- Code generated by dvo xql. DO NOT EDIT.
-- Generated at: 2025-12-17 17:31:10

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY,
    account_id BIGINT,
    amount DOUBLE PRECISION,
    created_at TIMESTAMP WITH TIME ZONE
);



