-- Code generated by dvo xql. DO NOT EDIT.
-- Generated at: 2025-12-20 02:29:13

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY,
    account_id BIGINT,
    amount DOUBLE,
    created_at DATETIME,
    updated_at DATETIME,
    created_by TEXT,
    updated_by TEXT
);

